config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    resource :session, only: %i[destroy]
    resource :profile, only: %i[show]

    resources :bulletins, only: %i[index show new create edit update] do
      member do
        patch :moderate, :archive
      end
    end

    namespace :admin do
      root 'admins#index'
      resources :categories, only: %i[index new create edit update destroy]

      resources :bulletins, only: %i[index] do
        member do
          patch :archive, :publish, :reject
        end
      end
    end
  end
end

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        = t('.title')
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to root_path, class: 'nav-link text-dark' do
              = t('.home')
          - if signed_in?
            li.nav-item.me-2
              = link_to profile_path, class: 'nav-link text-dark' do
                = t('.my_ads')
            li.nav-item.me-2
              = link_to new_bulletin_path, class: 'nav-link text-dark' do
                = t('.add')
    ul.nav.nav-pills
      - if signed_in?
        - if current_user.admin?
          li.nav-item.me-2
            = link_to admin_root_path, class: 'nav-link text-dark' do
              = t('.admin_panel')
        li.nav-item.me-2
          = link_to session_path, data: { turbo_method: :delete }, class: 'nav-link text-dark' do
            = t('.sign_out')
      - else
        li.nav-item.me-2
          = button_to auth_request_path('github'), data: { turbo: false }, class: 'nav-link text-dark' do
            span.bi.bi-github.me-2
            = t('.sign_in')