config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    resource :session, only: %i[destroy]
    resource :profile, only: %i[show]

    resources :bulletins, only: %i[index show new create edit update] do
      member do
        patch :moderate, :archive
      end
    end

    namespace :admin do
      root 'admins#index'
      resources :categories, only: %i[index new create edit update destroy]

      resources :bulletins, only: %i[index] do
        member do
          patch :archive, :publish, :reject
        end
      end
    end
  end
end

app/views/web/admin/admins/index.html.slim
- content_for :title do
  = t('.title')
h1.h2.mb-4 = t('.bulletins_under_moderation')
row.mt-2
  table.table.table-borderless
    thead
      tr
        th = t('.bulletin_name')
        th = t('.bulletin_created')
        th = t('.actions')
    tbody
      - @bulletins.each do |bulletin|
        tr
          td
            = link_to bulletin_path(bulletin) do
              = bulletin.title
          td
            = time_ago_in_words bulletin.created_at
          td
            - if bulletin.may_publish?
              = link_to publish_admin_bulletin_path(bulletin), data: { turbo_method: 'patch' }, class: 'me-1' do
                = t('.to_publish')
            - if bulletin.may_reject?
              = link_to reject_admin_bulletin_path(bulletin),
                      data: { turbo_method: 'patch', turbo_confirm: t('.confirm_rejecting') }, class: 'me-1' do
                = t('.to_reject')
            - if bulletin.may_archive?
              = link_to archive_admin_bulletin_path(bulletin),
                      data: { turbo_method: 'patch', turbo_confirm: t('.confirm_archiving') }, class: 'text-danger' do
                = t('.to_archive')
  .mt-2
    = paginate @bulletins