config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    resource :session, only: %i[destroy]
    resource :profile, only: %i[show]

    resources :bulletins, only: %i[index show new create edit update] do
      member do
        patch :moderate, :archive
      end
    end

    namespace :admin do
      root 'admins#index'
      resources :categories, only: %i[index new create edit update destroy]

      resources :bulletins, only: %i[index] do
        member do
          patch :archive, :publish, :reject
        end
      end
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :bulletins, inverse_of: :category, dependent: :restrict_with_error

  validates :name, presence: true

  scope :by_id_asc, -> { order(id: :asc) }
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

class Web::Admin::CategoriesController < Web::Admin::ApplicationController
  def index
    @categories = Category.by_id_asc
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find params[:id]
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path, notice: t('.success')
    else
      flash.now[:failure] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @category = Category.find params[:id]

    if @category.update(category_params)
      redirect_to admin_categories_path, notice: t('.success')
    else
      flash.now[:failure] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find params[:id]

    if @category.destroy
      redirect_to admin_categories_path, notice: t('.success')
    else
      redirect_to admin_categories_path, alert: t('.failure')
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/web/admin/categories/_form.html.slim
= simple_form_for([:admin, category]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :name
  .col-auto.my-1.d-flex.mt-2
    = f.button :submit, class: 'btn-primary flex-grow-2 me-2'

app/views/web/admin/categories/edit.html.slim
- content_for :title do
  = t('.title')
h1.h2.mb-4 = t('.edit_category')
== render 'form', category: @category

app/views/web/admin/categories/index.html.slim
- content_for :title do
  = t('.title')
h1.h2.mb-4 = t('.all_categories')
= link_to new_admin_category_path do
  = t('.add_category')
.row.mt-2
  table.table.table-borderless
    thead
      tr
        th = t('.category_id')
        th = t('.category_name')
        th = t('.actions')
    tbody
      - @categories.each do |category|
        tr
          td
            = category.id
          td
            = category.name
          td
            = link_to edit_admin_category_path(category), class: 'me-1' do
              = t('.edit')
            = link_to admin_category_path(category),
                    data: { turbo_method: :delete, turbo_confirm: t('.confirm_deleting') }, class: 'text-danger me-1' do
              = t('.delete')

app/views/web/admin/categories/new.html.slim
- content_for :title do
  = t('.title')
h1.h2.mb-4 = t('.new_category')
== render 'form', category: @category